DELETE FROM	mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');

ALTER USER 'root'@'localhost' IDENTIFIED BY '$MARIADB_ROOT_PASSWORD';

CREATE USER IF NOT EXISTS '$MARIADB_USER'@'localhost' IDENTIFIED BY '$MARIADB_PASSWORD';
SET PASSWORD FOR '$MARIADB_USER'@'localhost' = PASSWORD('$MARIADB_PASSWORD');

CREATE USER IF NOT EXISTS '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD';
SET PASSWORD FOR '$MARIADB_USER'@'%' = PASSWORD('$MARIADB_PASSWORD');

CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE;
GRANT ALL ON $MARIADB_DATABASE.* TO '$MARIADB_USER'@'localhost';
GRANT ALL ON $MARIADB_DATABASE.* TO '$MARIADB_USER'@'%';

FLUSH PRIVILEGES;
